name: ci

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "*.md"
  workflow_dispatch:

# Cancel in progress workflows
# in the scenario where we already had a run going for that PR/branch/tag but then triggered a new run
concurrency:
  group: "${{ github.workflow }} ✨ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install --ignore-scripts --include=dev

      - name: Run lint
        run: node --run lint # Use `node --run` to run the script in package.json

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
         
          - Node.js 18.x
          
          - Node.js 20.x
          

        include:
         
          - name: Node.js 18.x
            node-version: "18"


          - name: Node.js 20.x
            node-version: "20"

       

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install Node.js ${{ matrix.node-version }}
        shell: bash -eo pipefail -l {0}
        run: |
          nvm install --default ${{ matrix.node-version }}
          if [[ "${{ matrix.node-version }}" == 0.* && "$(cut -d. -f2 <<< "${{ matrix.node-version }}")" -lt 10 ]]; then
            nvm install --alias=npm 0.10
            nvm use ${{ matrix.node-version }}
            sed -i '1s;^.*$;'"$(printf '#!%q' "$(nvm which npm)")"';' "$(readlink -f "$(which npm)")"
            npm config set strict-ssl false
          fi
          dirname "$(nvm which ${{ matrix.node-version }})" >> "$GITHUB_PATH"

      - name: Configure npm
        run: |
          if [[ "$(npm config get package-lock)" == "true" ]]; then
            npm config set package-lock false
          else
            npm config set shrinkwrap false
          fi

      - name: Remove npm module(s) ${{ matrix.npm-rm }}
        run: npm rm --silent --save-dev ${{ matrix.npm-rm }}
        if: matrix.npm-rm != ''

      - name: Install npm module(s) ${{ matrix.npm-i }}
        run: npm install --save-dev ${{ matrix.npm-i }}
        if: matrix.npm-i != ''

      - name: Setup Node.js version-specific dependencies
        shell: bash
        run: |
          # eslint for linting
          # - remove on Node.js < 10
          if [[ "$(cut -d. -f1 <<< "${{ matrix.node-version }}")" -lt 10 ]]; then
            node -pe 'Object.keys(require("./package").devDependencies).join("\n")' | \
              grep -E '^eslint(-|$)' | \
              sort -r | \
              xargs -n1 npm rm --silent --save-dev
          fi

      - name: Install Node.js dependencies
        run: npm install

      - name: List environment
        id: list_env
        shell: bash
        run: |
          echo "node@$(node -v)"
          echo "npm@$(npm -v)"
          npm -s ls ||:
          (npm -s ls --depth=0 ||:) | awk -F'[ @]' 'NR>1 && $2 { print "::set-output name=" $2 "::" $3 }'

      - name: Run tests
        shell: bash
        run: |
          if npm -ps ls nyc | grep -q nyc; then
            npm run test-ci
            cp coverage/lcov.info "coverage/${{ matrix.node-version }}.lcov"
          else
            npm test
          fi

      - name: Collect code coverage
        if: steps.list_env.outputs.nyc != ''
        run: |
          if [[ -d ./coverage ]]; then
            mv ./coverage "./${{ matrix.node-version }}"
            mkdir ./coverage
            mv "./${{ matrix.node-version }}" "./coverage/${{ matrix.node-version }}"
          fi

      - name: Upload code coverage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: steps.list_env.outputs.nyc != ''
        with:
          name: coverage-${{ matrix.node-version }} # to avoid conflicts
          path: "./coverage/${{ matrix.node-version }}"
          retention-days: 1

  coverage:
    name: Coverage
    permissions:
      checks: write # for coverallsapp/github-action to create new checks
      contents: read # for actions/checkout to fetch code
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install lcov
        shell: bash
        run: sudo apt-get -y install lcov

      - name: Collect coverage reports
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: ./coverage

      - name: Merge coverage reports
        shell: bash
        run: find ./coverage -name lcov.info -exec printf '-a %q\n' {} \; | xargs lcov -o ./coverage/lcov.info

      - name: Upload coverage report
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          file: ./coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
